/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "/home/ourongxing/Blog/node_modules/@vuepress/core/lib/client/components/GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-7fa0df8e",
    path: "/technology/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7fa0df8e").then(next)
    },
  },
  {
    path: "/technology/index.html",
    redirect: "/technology/"
  },
  {
    path: "/00.%E7%9B%AE%E5%BD%95%E9%A1%B5/01.%E6%8A%80%E6%9C%AF.html",
    redirect: "/technology/"
  },
  {
    name: "v-58d82de1",
    path: "/digital/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-58d82de1").then(next)
    },
  },
  {
    path: "/digital/index.html",
    redirect: "/digital/"
  },
  {
    path: "/00.%E7%9B%AE%E5%BD%95%E9%A1%B5/02.%E6%95%B0%E7%A0%81.html",
    redirect: "/digital/"
  },
  {
    name: "v-edac3580",
    path: "/note/cpp/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-edac3580").then(next)
    },
  },
  {
    path: "/note/cpp/index.html",
    redirect: "/note/cpp/"
  },
  {
    path: "/01.%E6%8A%80%E6%9C%AF/00.%E5%AD%A6%E4%B9%A0%E7%AC%94%E8%AE%B0/00.Cpp%E7%AC%94%E8%AE%B0.html",
    redirect: "/note/cpp/"
  },
  {
    name: "v-e872a530",
    path: "/other/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e872a530").then(next)
    },
  },
  {
    path: "/other/index.html",
    redirect: "/other/"
  },
  {
    path: "/00.%E7%9B%AE%E5%BD%95%E9%A1%B5/03.%E5%85%B6%E4%BB%96.html",
    redirect: "/other/"
  },
  {
    name: "v-03a27560",
    path: "/pages/b27813/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-03a27560").then(next)
    },
  },
  {
    path: "/pages/b27813/index.html",
    redirect: "/pages/b27813/"
  },
  {
    path: "/03.%E5%85%B6%E4%BB%96/01.%E5%88%86%E4%BA%AB/01.%E7%AE%80%E9%99%8B%E7%9A%84%E5%AF%BC%E8%88%AA.html",
    redirect: "/pages/b27813/"
  },
  {
    name: "v-6e814736",
    path: "/pages/ebff14/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6e814736").then(next)
    },
  },
  {
    path: "/pages/ebff14/index.html",
    redirect: "/pages/ebff14/"
  },
  {
    path: "/03.%E5%85%B6%E4%BB%96/01.%E5%88%86%E4%BA%AB/00.%E4%BD%A0%E4%BC%9A%E7%94%A8chrome%E5%90%97%EF%BC%88%E4%B8%80%EF%BC%89.html",
    redirect: "/pages/ebff14/"
  },
  {
    name: "v-7233f924",
    path: "/about/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7233f924").then(next)
    },
  },
  {
    path: "/about/index.html",
    redirect: "/about/"
  },
  {
    path: "/05.%E5%85%B3%E4%BA%8E/01.%E5%85%B3%E4%BA%8E.html",
    redirect: "/about/"
  },
  {
    name: "v-651fe48a",
    path: "/categories/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-651fe48a").then(next)
    },
  },
  {
    path: "/categories/index.html",
    redirect: "/categories/"
  },
  {
    path: "/@pages/categoriesPage.html",
    redirect: "/categories/"
  },
  {
    name: "v-083e83aa",
    path: "/archives/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-083e83aa").then(next)
    },
  },
  {
    path: "/archives/index.html",
    redirect: "/archives/"
  },
  {
    path: "/@pages/archivesPage.html",
    redirect: "/archives/"
  },
  {
    name: "v-d40643ac",
    path: "/tags/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d40643ac").then(next)
    },
  },
  {
    path: "/tags/index.html",
    redirect: "/tags/"
  },
  {
    path: "/@pages/tagsPage.html",
    redirect: "/tags/"
  },
  {
    name: "v-7cc679f2",
    path: "/pages/766282/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7cc679f2").then(next)
    },
  },
  {
    path: "/pages/766282/index.html",
    redirect: "/pages/766282/"
  },
  {
    path: "/Cpp%E7%AC%94%E8%AE%B0/10.%E7%BB%A7%E6%89%BF%E4%B8%8E%E6%B4%BE%E7%94%9F.html",
    redirect: "/pages/766282/"
  },
  {
    name: "v-24ed466d",
    path: "/friends/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-24ed466d").then(next)
    },
  },
  {
    path: "/friends/index.html",
    redirect: "/friends/"
  },
  {
    path: "/_posts/99.%E5%8F%8B%E6%83%85%E9%93%BE%E6%8E%A5.html",
    redirect: "/friends/"
  },
  {
    name: "v-9163e4fa",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9163e4fa").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]