/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Oh! My Blog",
  "description": "天生骄傲",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/img/favicon.ico"
      }
    ],
    [
      "meta",
      {
        "name": "keywords",
        "content": "前端博客,个人技术博客,前端,前端开发,前端框架,web前端,前端面试题,技术文档,学习,面试,JavaScript,js,ES6,TypeScript,vue,python,css3,html5,Node,git,github,markdown"
      }
    ],
    [
      "meta",
      {
        "name": "baidu-site-verification",
        "content": "7F55weZDDc"
      }
    ],
    [
      "meta",
      {
        "name": "theme-color",
        "content": "#11a8cd"
      }
    ]
  ],
  "pages": [
    {
      "title": "技术",
      "frontmatter": {
        "pageComponent": {
          "name": "Catalogue",
          "data": {
            "key": "01.技术",
            "imgUrl": "/img/web.png",
            "description": "学得很杂什么都会一点"
          }
        },
        "title": "技术",
        "date": "2020-03-11T21:50:53.000Z",
        "permalink": "/technology",
        "sidebar": false,
        "article": false,
        "comment": true,
        "editLink": false
      },
      "regularPath": "/00.%E7%9B%AE%E5%BD%95%E9%A1%B5/01.%E6%8A%80%E6%9C%AF.html",
      "relativePath": "00.目录页/01.技术.md",
      "key": "v-7fa0df8e",
      "path": "/technology/"
    },
    {
      "title": "数码",
      "frontmatter": {
        "pageComponent": {
          "name": "Catalogue",
          "data": {
            "key": "02.数码",
            "imgUrl": "/img/ui.png",
            "description": "数码产品的使用体验"
          }
        },
        "title": "数码",
        "date": "2020-03-11T21:50:54.000Z",
        "permalink": "/digital",
        "sidebar": false,
        "article": false,
        "comment": true,
        "editLink": false
      },
      "regularPath": "/00.%E7%9B%AE%E5%BD%95%E9%A1%B5/02.%E6%95%B0%E7%A0%81.html",
      "relativePath": "00.目录页/02.数码.md",
      "key": "v-58d82de1",
      "path": "/digital/"
    },
    {
      "title": "C++笔记",
      "frontmatter": {
        "pageComponent": {
          "name": "Catalogue",
          "data": {
            "key": "Cpp笔记",
            "imgUrl": "https://cdn.jsdelivr.net/gh/xugaoyi/image_store/blog/20200204143633.png",
            "description": "C++的学习笔记"
          }
        },
        "title": "C++笔记",
        "date": "2020-02-04T12:16:12.000Z",
        "permalink": "/note/cpp",
        "article": false,
        "comment": false,
        "editLink": false
      },
      "regularPath": "/01.%E6%8A%80%E6%9C%AF/00.%E5%AD%A6%E4%B9%A0%E7%AC%94%E8%AE%B0/00.Cpp%E7%AC%94%E8%AE%B0.html",
      "relativePath": "01.技术/00.学习笔记/00.Cpp笔记.md",
      "key": "v-edac3580",
      "path": "/note/cpp/"
    },
    {
      "title": "其他",
      "frontmatter": {
        "pageComponent": {
          "name": "Catalogue",
          "data": {
            "key": "03.其他",
            "imgUrl": "/img/other.png",
            "description": "包罗万象"
          }
        },
        "title": "其他",
        "date": "2020-03-11T21:50:55.000Z",
        "permalink": "/other",
        "sidebar": false,
        "article": false,
        "comment": true,
        "editLink": false
      },
      "regularPath": "/00.%E7%9B%AE%E5%BD%95%E9%A1%B5/03.%E5%85%B6%E4%BB%96.html",
      "relativePath": "00.目录页/03.其他.md",
      "key": "v-e872a530",
      "path": "/other/"
    },
    {
      "title": "简陋的导航",
      "frontmatter": {
        "title": "简陋的导航",
        "date": "2019-07-09T00:00:00.000Z",
        "categories": [
          "分享"
        ],
        "permalink": "/pages/b27813/",
        "sticky": 1,
        "tags": [
          "网站分享"
        ]
      },
      "regularPath": "/03.%E5%85%B6%E4%BB%96/01.%E5%88%86%E4%BA%AB/01.%E7%AE%80%E9%99%8B%E7%9A%84%E5%AF%BC%E8%88%AA.html",
      "relativePath": "03.其他/01.分享/01.简陋的导航.md",
      "key": "v-03a27560",
      "path": "/pages/b27813/",
      "headers": [
        {
          "level": 3,
          "title": "📖 更新日志",
          "slug": "更新日志"
        },
        {
          "level": 3,
          "title": "🎞 在线视频",
          "slug": "在线视频"
        },
        {
          "level": 3,
          "title": "🔩 破解软件",
          "slug": "破解软件"
        },
        {
          "level": 3,
          "title": "📓 免费小说",
          "slug": "免费小说"
        },
        {
          "level": 3,
          "title": "💾 云盘搜索",
          "slug": "云盘搜索"
        },
        {
          "level": 3,
          "title": "🔍 搜索引擎",
          "slug": "搜索引擎"
        },
        {
          "level": 3,
          "title": "🚢 Onedrive 资源站",
          "slug": "onedrive-资源站"
        }
      ],
      "excerpt": "<div class=\"custom-block tip\"><p class=\"custom-block-title\">持续更新</p>\n<p>分享一些特殊的网站<br>\n欢迎在下方留言补充更多网站</p>\n</div>\n"
    },
    {
      "title": "你会用 Chrome 吗（扩展篇）",
      "frontmatter": {
        "title": "你会用 Chrome 吗（扩展篇）",
        "date": "2019-07-14T00:00:00.000Z",
        "categories": [
          "分享"
        ],
        "tags": [
          "Chrome",
          "分享"
        ],
        "permalink": "/pages/ebff14/"
      },
      "regularPath": "/03.%E5%85%B6%E4%BB%96/01.%E5%88%86%E4%BA%AB/00.%E4%BD%A0%E4%BC%9A%E7%94%A8chrome%E5%90%97%EF%BC%88%E4%B8%80%EF%BC%89.html",
      "relativePath": "03.其他/01.分享/00.你会用chrome吗（一）.md",
      "key": "v-6e814736",
      "path": "/pages/ebff14/",
      "headers": [
        {
          "level": 2,
          "title": "前言",
          "slug": "前言"
        },
        {
          "level": 2,
          "title": "准备",
          "slug": "准备"
        },
        {
          "level": 3,
          "title": "下载 Chrome",
          "slug": "下载-chrome"
        },
        {
          "level": 3,
          "title": "安装谷歌上网助手",
          "slug": "安装谷歌上网助手"
        },
        {
          "level": 3,
          "title": "注册 Google 账号",
          "slug": "注册-google-账号"
        },
        {
          "level": 2,
          "title": "扩展推荐",
          "slug": "扩展推荐"
        },
        {
          "level": 3,
          "title": "uBlock Origin",
          "slug": "ublock-origin"
        },
        {
          "level": 3,
          "title": "Stylus",
          "slug": "stylus"
        },
        {
          "level": 3,
          "title": "Tampermonkey",
          "slug": "tampermonkey"
        },
        {
          "level": 3,
          "title": "Chrome Better History",
          "slug": "chrome-better-history"
        },
        {
          "level": 3,
          "title": "Vimium",
          "slug": "vimium"
        },
        {
          "level": 3,
          "title": "彩云小译",
          "slug": "彩云小译"
        },
        {
          "level": 3,
          "title": "沙拉查词",
          "slug": "沙拉查词"
        },
        {
          "level": 3,
          "title": "Proxy SwitchyOmega",
          "slug": "proxy-switchyomega"
        },
        {
          "level": 3,
          "title": "Octotree",
          "slug": "octotree"
        }
      ],
      "excerpt": "<blockquote>\n<p>本文主要介绍 Chrome 扩展的食用，长期更新</p>\n</blockquote>\n<h2 id=\"前言\"><a class=\"header-anchor\" href=\"#前言\">#</a> 前言</h2>\n<p>有个段子这样说，<strong>win10 上 IE 存在的唯一价值就是用来下载 Chrome</strong></p>\n<p>Chrome 是目前浏览器界当之无愧的霸主，除了更快、功能更强大外，更是因为 Google 将 Chrome 开源，也就是 Chromium 项目，任何人都可以基于 Chromium 开发自己的浏览器，国内的浏览器大多都是基于 Chromium ，加了本地化的功能，然而也加入了广告，我非常不建议使用这些大厂浏览器</p>\n"
    },
    {
      "title": "关于",
      "frontmatter": {
        "title": "关于",
        "date": "2019-12-25T14:27:01.000Z",
        "permalink": "/about",
        "sidebar": false,
        "article": false
      },
      "regularPath": "/05.%E5%85%B3%E4%BA%8E/01.%E5%85%B3%E4%BA%8E.html",
      "relativePath": "05.关于/01.关于.md",
      "key": "v-7233f924",
      "path": "/about/",
      "headers": [
        {
          "level": 3,
          "title": "🐼Me",
          "slug": "🐼me"
        },
        {
          "level": 2,
          "title": "✉️ 联系",
          "slug": "联系"
        }
      ]
    },
    {
      "title": "分类",
      "frontmatter": {
        "categoriesPage": true,
        "title": "分类",
        "permalink": "/categories/",
        "article": false
      },
      "regularPath": "/@pages/categoriesPage.html",
      "relativePath": "@pages/categoriesPage.md",
      "key": "v-651fe48a",
      "path": "/categories/"
    },
    {
      "title": "归档",
      "frontmatter": {
        "archivesPage": true,
        "title": "归档",
        "permalink": "/archives/",
        "article": false
      },
      "regularPath": "/@pages/archivesPage.html",
      "relativePath": "@pages/archivesPage.md",
      "key": "v-083e83aa",
      "path": "/archives/"
    },
    {
      "title": "标签",
      "frontmatter": {
        "tagsPage": true,
        "title": "标签",
        "permalink": "/tags/",
        "article": false
      },
      "regularPath": "/@pages/tagsPage.html",
      "relativePath": "@pages/tagsPage.md",
      "key": "v-d40643ac",
      "path": "/tags/"
    },
    {
      "title": "继承与派生",
      "frontmatter": {
        "title": "继承与派生",
        "date": "2019-12-14T23:06:01.000Z",
        "categories": [
          "Cpp笔记"
        ],
        "permalink": "/pages/766282/",
        "tags": [
          "Cpp"
        ]
      },
      "regularPath": "/Cpp%E7%AC%94%E8%AE%B0/10.%E7%BB%A7%E6%89%BF%E4%B8%8E%E6%B4%BE%E7%94%9F.html",
      "relativePath": "Cpp笔记/10.继承与派生.md",
      "key": "v-7cc679f2",
      "path": "/pages/766282/",
      "headers": [
        {
          "level": 3,
          "title": "什么是继承，什么是派生",
          "slug": "什么是继承，什么是派生"
        },
        {
          "level": 3,
          "title": "如何继承",
          "slug": "如何继承"
        },
        {
          "level": 3,
          "title": "继承方式是干啥的",
          "slug": "继承方式是干啥的"
        },
        {
          "level": 3,
          "title": "基类和派生类，到底谁包含了谁",
          "slug": "基类和派生类，到底谁包含了谁"
        },
        {
          "level": 3,
          "title": "构造、析构函数这些也能被继承吗",
          "slug": "构造、析构函数这些也能被继承吗"
        },
        {
          "level": 3,
          "title": "如何多继承",
          "slug": "如何多继承"
        }
      ],
      "excerpt": "<blockquote>\n<p>继承性是面向对象语言最为重要的一个特征，大多数人也是从继承开始体会到C++的难度了，我也是一直没太搞清楚，这里来分享一下自己的理解，欢迎提出意见和建议</p>\n</blockquote>\n<h3 id=\"什么是继承，什么是派生\"><a class=\"header-anchor\" href=\"#什么是继承，什么是派生\">#</a> 什么是继承，什么是派生</h3>\n<p>从字面上就很清楚了，父母派生出了孩子，儿子继承了父母的财产，就是生孩子和继承财产的关系，本质上没什么区别。我最早接触派生这个词是在英语，派生是单词的一种构造方法，通过加一些前缀或者后缀来产生新的单词，这里的派生也是类似。</p>\n"
    },
    {
      "title": "友情链接",
      "frontmatter": {
        "title": "友情链接",
        "date": "2019-12-25T14:27:01.000Z",
        "permalink": "/friends",
        "article": false,
        "sidebar": false
      },
      "regularPath": "/_posts/99.%E5%8F%8B%E6%83%85%E9%93%BE%E6%8E%A5.html",
      "relativePath": "_posts/99.友情链接.md",
      "key": "v-24ed466d",
      "path": "/friends/",
      "headers": [
        {
          "level": 3,
          "title": "友链申请",
          "slug": "友链申请"
        }
      ]
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "Oh! My Blog",
        "tagline": "天生骄傲",
        "features": [
          {
            "title": "技术",
            "details": "学得很杂什么都会一点",
            "link": "/technology/",
            "imgUrl": "/img/web.png"
          },
          {
            "title": "数码",
            "details": "数码产品的使用体验",
            "link": "/digital/",
            "imgUrl": "/img/ui.png"
          },
          {
            "title": "其他",
            "details": "包罗万象",
            "link": "/other/",
            "imgUrl": "/img/other.png"
          }
        ]
      },
      "regularPath": "/",
      "relativePath": "index.md",
      "key": "v-9163e4fa",
      "path": "/"
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "首页",
        "link": "/"
      },
      {
        "text": "索引",
        "link": "/archives/",
        "items": [
          {
            "text": "分类",
            "link": "/categories/"
          },
          {
            "text": "标签",
            "link": "/tags/"
          },
          {
            "text": "归档",
            "link": "/archives/"
          }
        ]
      },
      {
        "text": "导航",
        "link": "https://orxing.top/nav"
      },
      {
        "text": "友链",
        "link": "/friends/"
      },
      {
        "text": "关于",
        "link": "/about/"
      }
    ],
    "sidebarDepth": 2,
    "logo": "/img/logo.png",
    "repo": "ourongxing/ourongxing.github.io",
    "searchMaxSuggestions": 10,
    "lastUpdated": "上次更新",
    "docsDir": "docs",
    "editLinks": true,
    "editLinkText": "编辑",
    "sidebar": {
      "/00.目录页/": [
        [
          "01.技术.md",
          "技术",
          "/technology"
        ],
        [
          "02.数码.md",
          "数码",
          "/digital"
        ],
        [
          "03.其他.md",
          "其他",
          "/other"
        ]
      ],
      "catalogue": {
        "技术": "/technology",
        "数码": "/digital",
        "其他": "/other",
        "Cpp笔记": "/note/cpp"
      },
      "/01.技术/": [
        {
          "title": "学习笔记",
          "collapsable": true,
          "children": [
            [
              "00.学习笔记/00.Cpp笔记.md",
              "Cpp笔记",
              "/note/cpp"
            ]
          ]
        }
      ],
      "/03.其他/": [
        {
          "title": "分享",
          "collapsable": true,
          "children": [
            [
              "01.分享/00.你会用chrome吗（一）.md",
              "你会用chrome吗（一）",
              "/pages/ebff14/"
            ],
            [
              "01.分享/01.简陋的导航.md",
              "简陋的导航",
              "/pages/b27813/"
            ]
          ]
        }
      ],
      "/05.关于/": [
        [
          "01.关于.md",
          "关于",
          "/about"
        ]
      ],
      "/Cpp笔记/": [
        [
          "10.继承与派生.md",
          "继承与派生",
          "/pages/766282/"
        ]
      ],
      "/_posts/": [
        [
          "99.友情链接.md",
          "友情链接",
          "/friends"
        ]
      ]
    },
    "author": {
      "name": "ourongxing",
      "link": "https://github.com/ourongxing"
    },
    "blogger": {
      "avatar": "/img/logo.png",
      "name": "ourongxing",
      "slogan": "天生骄傲"
    },
    "social": {
      "icons": [
        {
          "iconClass": "icon-github",
          "title": "GitHub",
          "link": "https://github.com/ourongxing"
        },
        {
          "iconClass": "icon-zhihu",
          "title": "知乎",
          "link": "https://www.zhihu.com/people/ourongxing/answers"
        },
        {
          "iconClass": "icon-telegram",
          "title": "Telegram",
          "link": "https://t.me/orongxing"
        },
        {
          "iconClass": "icon-gmail",
          "title": "发邮件",
          "link": "mailto:orongxing@gmail.com"
        },
        {
          "iconClass": "icon-qq",
          "title": "QQ",
          "link": "tencent://Message/?Uin=2836664669&amp;websiteName=q-zone.qq.com&amp;Menu=yes"
        }
      ]
    },
    "footer": {
      "createYear": 2019,
      "ICP": {
        "url": "http://icp.chinaz.com/record/orxing.top",
        "text": "渝ICP备19005638号"
      },
      "copyrightInfo": "<a href=\"https://github.com/xugaoyi/vuepress-theme-vdoing/blob/master/LICENSE\" target=\"_blank\">MIT License</a>"
    }
  }
}